---
- name: 'Create Kubernetes secret for AWX TLS certificate'
  hosts: 'all'
  gather_facts: true
  become: false

  tasks:

    - name: create awx-tls secret
      delegate_to: localhost
      k8s:
        # kubeconfig
        kubeconfig: 'k3s-kubeconfig'
        # actual object in kubernetes
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          type: kubernetes.io/tls
          metadata:
            name: awx-tls
            namespace: awx
          data:
            tls.crt: "{{ (lookup('file', './awx.crt') + '\n') | b64encode }}"
            tls.key: "{{ (lookup('file', './awx.key') + '\n') | b64encode }}"
