---

- name: 'Run playbook-bootstrap_python.yml'
  ansible.builtin.import_playbook: playbook-bootstrap_python.yml

- name: 'Run playbook-install_k3s.yml'
  ansible.builtin.import_playbook: playbook-install_k3s.yml

- name: 'Run playbook-create_certificate.yml'
  ansible.builtin.import_playbook: playbook-create_certificate.yml

- name: 'Run playbook-all_nodes-kubernetes_preparation.yml'
  ansible.builtin.import_playbook: playbook-all_nodes-kubernetes_preparation.yml

- name: 'Run playbook-all_nodes-kubernetes_secret_for_awx.yml'
  ansible.builtin.import_playbook: playbook-all_nodes-kubernetes_secret_for_awx.yml

- name: 'Run playbook-all_nodes-awx_operator_per_ansible_kustomize.yml'
  ansible.builtin.import_playbook: playbook-all_nodes-awx_operator_per_ansible_kustomize.yml

- name: 'Run playbook-all_nodes-install_awx_in_kubernetes.yml'
  ansible.builtin.import_playbook: playbook-all_nodes-install_awx_in_kubernetes.yml
