---

- name: 'Run playbook-bootstrap_python.yml'
  ansible.builtin.import_playbook: playbook-bootstrap_python.yml

- name: 'Run playbook-install_k3s.yml'
  ansible.builtin.import_playbook: playbook-install_k3s.yml

- name: 'Run playbook-k3s_configure_private_registries.yml'
  ansible.builtin.import_playbook: playbook-k3s_configure_private_registries.yml

- name: 'Run playbook-create_certificate.yml'
  ansible.builtin.import_playbook: playbook-create_certificate.yml

- name: 'Run playbook-kubernetes_preparation.yml'
  ansible.builtin.import_playbook: playbook-kubernetes_preparation.yml

- name: 'Run playbook-kubernetes_secret_for_awx.yml'
  ansible.builtin.import_playbook: playbook-kubernetes_secret_for_awx.yml

- name: 'Run playbook-awx_operator_per_ansible_kustomize.yml'
  ansible.builtin.import_playbook: playbook-awx_operator_per_ansible_kustomize.yml

- name: 'Run playbook-install_awx_in_kubernetes.yml'
  ansible.builtin.import_playbook: playbook-install_awx_in_kubernetes.yml
